project:
  type: book
  render:
    - "*.qmd"

book:
  title: "CRRESS"
  repo-url: https://github.com/amichuda/crress-book
  repo-actions: [edit]
  downloads: [pdf]
  navbar:
    search: true
    pinned: true
    logo: "images/LDI Conf CRRESS V4.png"
    # background: "#f8f8f8"
  subtitle: Conference on Reproducibility and Replicability in Economics and the Social Sciences
  cover-image: "images/LDI Conf CRRESS V4.png"
  page-navigation: true
  page-footer: 
    # background: "#f8f8f8"
    left: "Copyright 2022, CRRESS"
    right:
      - icon: github
        href: https://github.com/amichuda/crress-book/
  # reader-mode: true
  search: true
  chapters:
    - index.qmd
    - events.qmd
    - about.qmd
    - part: sessions/session1/session1_intro.qmd
      chapters:
        - sessions/session1/salmon/index.qmd
        - sessions/session1/whited/index.qmd
    - part: sessions/session2/session2_intro.qmd
      chapters:
        - sessions/session2/swauger/index.qmd
    - part: sessions/session3/session3_intro.qmd
      chapters:
        - sessions/session3/diego/index.qmd
    - part: sessions/session4/session4_intro.qmd
      chapters:
        - sessions/session4/guimaraes/index.qmd
    - part: sessions/session5/session5_intro.qmd
      chapters:
        - sessions/session5/hoynes/index.qmd
    - part: sessions/session7/session7_intro.qmd
      chapters:
        - sessions/session7/macdonald/index.qmd
format:
  html:
    theme: 
      light: minty
      dark: darkly
    # css: styles.css
    toc: true
    number-sections: false
  pdf:
    documentclass: scrreport
execute:
  freeze: auto


