project:
  type: book
  render:
    - "*.qmd"

book:
  title: "CRRESS"
  cover-image: "images/LDI Conf CRRESS V4.png"
  page-navigation: true
  page-footer: "Copyright 2022, CRRESS"
  reader-mode: true
  search: true
  chapters:
    - index.qmd
    - events.qmd
    - about.qmd
    - part: sessions/session1/session1_intro.qmd
      chapters:
        - sessions/session1/converted/paper1/paper1.qmd
        - sessions/session1/converted/paper2/paper2.qmd
        - sessions/session1/converted/paper3/paper3.qmd
    - part: sessions/session2/session2_intro.qmd
      chapters:
        - sessions/session2/converted/paper4/paper4.qmd
        - sessions/session2/converted/paper5/paper5.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreport
execute:
  freeze: auto


